name: gradle-tests.yml

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests with Gradle
        run: ./gradlew test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always() # Upload even if tests fail
        with:
          name: test-results
          path: |
            build/test-results/test/**
            build/reports/tests/test/**
      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Test Results
          path: build/test-results/test/*.xml  # Recursive glob
          reporter: java-junit
          fail-on-error: false  # Continue job even if reporting fails
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}